services:
  - type: web
    name: miniapp-telegram
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --bind 0.0.0.0:$PORT web:app
    envVars:
      - key: START_TELEGRAM_BOT
        value: "true"
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BOT_ADMIN_PASSWORD
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: SECRET_KEY
        generateValue: true
